# Generated by Django 4.2 on 2024-04-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flashcard',
            name='public_flashcards_index',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='private',
        ),
    ]
